sudo: required

language: golang

services:
    - docker

before_install:
    - docker pull schmidtw/webpa.builder.centos6:latest
    - docker run -it -d --name build schmidtw/webpa.builder.centos6 bash
    - docker exec build git clone https://github.com/Comcast/petasos.git
    - docker exec build bash -c "pushd petasos; git fetch; git checkout travis-testing; popd"
    - docker exec build bash -c "mv petasos petasos-1.1.0; tar -czvf petasos-1.1.0.tar.gz petasos-1.1.0; mv petasos-1.1.0.tar.gz /root/rpmbuild/SOURCES"
    - docker exec build bash -c "pushd petasos-1.1.0; rpmbuild -ba petasos.spec; popd"

script:
    - docker exec build rpmbuild -ba -H/product -B/

#after_success:
#    - bash <(curl -s https://codecov.io/bash)
#    - rpmbuild -bb --define "_buildnumber $TRAVIS_BUILD_NUMBER" petasos.spec
