sudo: required

language: golang

services:
    - docker

before_install:
    - docker pull schmidtw/webpa.builder.centos6:latest
    - docker run -it -d --name build schmidtw/webpa.builder.centos6 bash
    - docker exec build git clone https://github.com/Comcast/petasos.git

script:
    - docker exec build rpmbuild -ba -H/product -B/

#after_success:
#    - bash <(curl -s https://codecov.io/bash)
#    - rpmbuild -bb --define "_buildnumber $TRAVIS_BUILD_NUMBER" petasos.spec
