dist: trusty
sudo: required

language: go
go: 
    - 1.7.3

env:
    - TEST_DIR=src/petasos

before_install:
    - sudo pip install codecov rpm

script:
    - tar --transform "s/^\./petasos-1.0/" -czf petasos-1.0.tar.gz .
    - cd $TEST_DIR && go test -coverprofile=coverage.txt

after_success:
    - bash <(curl -s https://codecov.io/bash)
    - rpmbuild -bb --define "_buildnumber $TRAVIS_BUILD_NUMBER" petasos.spec
