sudo: required

services:
    - docker

before_install:
    - docker pull schmidtw/webpa.builder.centos6:latest
    - docker run -it -e BUILD_NUMBER=$TRAVIS_BUILD_NUMBER -d --name build schmidtw/webpa.builder.centos6 bash
    - docker exec build git clone https://github.com/sholaday/petasos.git

script:
    - docker exec build bash -c "pushd petasos; git fetch; git checkout travis-testing; popd"
    - docker exec build bash -c "pushd petasos; ./build_rpm.sh; popd"
    - docker exec build bash -c "mv petasos petasos-$RELEASE_NO; tar -czvf petasos-$RELEASE_NO.tar.gz petasos-$RELEASE_NO; mv petasos-$RELEASE_NO.tar.gz /root/rpmbuild/SOURCES"
    - docker exec build bash -c "pushd /root/rpmbuild; ls -R; popd; echo \"$RELEASE_NO\""
    - docker exec build bash -c "pushd petasos-$RELEASE_NO; rpmbuild -ba petasos.spec; popd"

# after_success:
#     - bash <(curl -s https://codecov.io/bash)
#     - rpmbuild -bb --define "_buildnumber $TRAVIS_BUILD_NUMBER" petasos.spec
