language: go
go: 
    - 1.7.3

env:
    - TEST_DIR=src/petasos

before_install:
    - sudo pip install --user codecov

script:
    - cd $TEST_DIR && go test -coverprofile=coverage.txt

after_success:
    - bash <(curl -s https://codecov.io/bash)
