sudo: required

services:
    - docker

before_install:
    - docker pull schmidtw/webpa.builder.centos6:latest
    - docker run -it -e BUILD_NUMBER=$TRAVIS_BUILD_NUMBER -d --name build schmidtw/webpa.builder.centos6 bash
    - docker exec build git clone https://github.com/sholaday/petasos.git

script:
    - docker exec build bash -c "pushd petasos; ./build_rpm.sh; popd"

after_success:
    - docker cp build:/root/rpmbuild/RPMS/x86_64 .
    - docker cp build:/versionno.txt .
    - BINARY_NAME=`ls x86_64/`
    - RELEASE_TAG=`cat versionno.txt`
    - git clone https://github.com/sholaday/petasos.git
    - cd petasos
    - git config credential.helper "store --file=.git/credentials"
    - echo "https://${AUTH_TOKEN_BUILD}:@github.com" > .git/credentials
    - git tag $RELEASE_TAG
    - git push --tags

deploy:
  provider: releases
  prerelease: true
  api_key: $AUTH_TOKEN_BUILD
  file: ~/build/sholaday/petasos/x86_64/$BINARY_NAME
  skip_cleanup: true
  on:
    tags: true
    branch: master

