sudo: required

services:
    - docker

branches:
    only:
    - master

before_install:
    - docker pull schmidtw/webpa.builder.centos6:latest
    - docker run -it -e BUILD_NUMBER=$TRAVIS_BUILD_NUMBER -d --name build schmidtw/webpa.builder.centos6 bash
    - docker exec build git clone https://github.com/Comcast/petasos.git
    - docker exec build git clone https://github.com/Comcast/petasos.git codecovio_build

script:
    - docker exec build bash -c "export GOPATH=/codecovio_build && pushd codecovio_build/src && glide install && cd petasos && go build petasos && go test && popd"
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker exec build bash -c "pushd petasos; ./build_rpm.sh; popd"; fi'

after_success:
    - docker exec build bash <(curl -s https://codecov.io/bash) -s codecovio_build || echo "Codecov did not collect coverage reports"
    - docker cp build:/root/rpmbuild/RPMS/x86_64 .
    - docker cp build:/versionno.txt .
    - BINARY_NAME=`ls x86_64/`
    - TRAVIS_TAG=`cat versionno.txt`

deploy:
  provider: releases
  prerelease: true
  api_key: $AUTH_TOKEN_BUILD
  file: x86_64/$BINARY_NAME
  skip_cleanup: true
  on:
    condition: "$TRAVIS_PULL_REQUEST = false"

